---
- name: Hello
  hosts: all
  gather_facts: False
  sources:
    - listen:
  rules:
    - name: Hello
      condition: event.text == 'hello ansible'
      action:
        say:
          text: "Hello"
    - name: Greeting
      condition: event.text == 'i am ben'
      action:
        say:
          text: "Nice to meet you Ben"
...
