---
- name: Hello
  hosts: all
  gather_facts: False
  sources:
    - listen:
  rules:
    - name: Hello
      condition: event.text == 'hello computer'
      action:
        say:
          text: "Hello"
    - name: Thank you
      condition: event.text == 'thank you'
      action:
        say:
          text: "You're welcome"
    - name: Greeting
      condition: event.text == 'i am ben'
      action:
        say:
          text: "Nice to meet you Ben"
    - name: JSON Post
      condition: event.text == 'post please'
      action:
        json_post:
          uri: http://localhost:8000/webhook
          data:
            message: hi
    - name: Goodbye
      condition: event.text == 'goodbye'
      actions:
      - say:
          text: "bye bye"
      - shutdown:
          delay: 0
          kind: now
          message: "shut down now!!"
...
