---
- name: Hello
  hosts: all
  gather_facts: False
  sources:
    - listen:
  rules:
    - name: Hello
      condition: event.text == 'hello'
      action:
        say:
          text: "Hello"
    - name: Greeting
      condition: event.text == 'i am ben'
      action:
        say:
          text: "Nice to meet you Ben"
    - name: Goodbye
      condition: event.text == 'goodbye'
      action:
        shutdown:
          delay: 0
...
